config/routes.rb
Rails.application.routes.draw do
  resources :djs
  resources :business_hours, except: [:show, :edit, :update]
  resources :businesses
  resources :locations
  root 'welcome#index'
  get 'search_locations', to: 'locations#search'
  get 'find_locations', to: 'locations#find'
  get 'my_portfolio', to: 'locations#my_portfolio'
  get 'results', to: 'locations#result'
  get 'businesses/:id/edit_operations', to: 'businesses#edit_operations', as: "edit_operations"
  post 'businesses/:id/update_operations', to: 'businesses#update_operations', as: "update_operations" 

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: [:show, :edit, :update, :destroy, :new_operations, :create_operations, :edit_operations, :update_operations]

  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = Business.all
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
  end

  # GET /businesses/new
  def new
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(business_params)

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url, notice: 'Business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def new_operations
    @hour = Hour.new

  end

  def add_operations
    businesshours = @business.hours
    open_time = Time.new(1,1,1,params[:openhour].to_i, params[:openmin].to_i)
    close_time = Time.new(1,1,1,params[:closehour].to_i, params[:closemin].to_i)
    @hour = Hour.new
    @hour.weekday = params[:weekday]
    @hour.opening = open_time
    @hour.closing = close_time

    if @hour.save
        businesshours << @hour
    else
        render :new

    end
  end

  def create_operations
    #create button only available to businesses without hours of operations
    days = days_of_week
    days.each do |day| 
      hour= Time.new
      hour.weekday = day
      @business.hours << hour
    end
    if @business.hours.save
      format.html { redirect_to edit_operations_path, notice: 'Hour of operation was successfully created.' }
    else
      format.html { render :new }
    end
  end

  def edit_operations
    #edit option only available to businesses without existing hours of operations


  end

  def update_operations

  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.require(:business).permit(:name, :owner, :category)
    end

    def days_of_week
      days = ["Mon", "Tues", "Wed", "Thurs", "Fri", "Sat", "Sun"]
    end


end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<%= form_for(@business) do |f| %>
  <% if @business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% @business.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :owner %><br>
    <%= f.text_field :owner %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/businesses/_hours.html.erb
<h2>Hours of Operation</h2>

app/views/businesses/_operation.html.erb
<!-- show and edit page will render this partial
if @business.hours.each already exists, then render that, but if not exists, create 7 days hours and @business.hours << -->

<%= form_tag add_operations_path, method: :get do %>
	<% @business.hours.each do |f| %>
		<div class= "form-group row no-padding text-center col-md-12">
			<div class="field">
				<%= label_tag "Weekday" %><br>
				<%= text_field_tag params[:weekday] %>
			</div>
			<div class="field">
				<%= label_tag "Open hour" %><br>
				<%= text_field_tag params[:openhour] %>
			</div>
			<div class="field">
		    	<%= label_tag "Open min" %><br>
			    <%= text_field_tag params[:openmin] %>
			</div>
		  	<div class="field">
				<%= label_tag "Close hour" %><br>
			    <%= text_field_tag params[:closehour] %>
			</div>
			<div class="field">
			    <%= label_tag "Close min" %><br>
			    <%= text_field_tag params[:closemin] %>
			</div>
	  	</div>
  	<% end %>
<% end %>

<!-- submit button will be on the edit page. this is just a partial -->

app/views/businesses/edit.html.erb
<h1>Editing Business</h1>

<%= render 'form' %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<p id="notice"><%= notice %></p>

<h1 id="VenueName">Listing Businesses</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Owner</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @businesses.each do |business| %>
      <tr>
        <td class = "name"><%= business.name %></td>
        <td><%= business.owner %></td>
        <td><%= business.category %></td>
        <td><%= link_to 'Show', business %></td>
        <td><%= link_to 'Edit', edit_business_path(business) %></td>
        <td><%= link_to 'Destroy', business, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
  
</table>

<br>

<div id="pasted" class = "well col-md-6"></div>

<%= link_to 'New Business', new_business_path %>


<script>
  $(document).ready(function(){
    $('#VenueName').click(function(){
      alert($(this).text());
      $('#pasted').html("<%= render partial: 'hours' %>").attr("h2");

    });

    $('.name').click(function(){
      alert($(this).html());
    });
  })
</script>

app/views/businesses/new.html.erb
<h1>New Business</h1>

<%= render 'form' %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/new_operations.html.erb
<%= render 'operation' %>

  <div class="actions">
    <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
      Add Operations
    <% end %>
  </div>

app/views/businesses/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-10">
	<p>
	  <strong>Name:</strong>
	  <%= @business.name %>
	</p>

	<p>
	  <strong>Owner:</strong>
	  <%= @business.owner %>
	</p>

	<p>
	  <strong>Category:</strong>
	  <%= @business.category %>
	</p><br/>
</div>

<div class="col-md-10">
	<p><strong> Hours of Operation </strong></p><br/>
	<% @business.hours.each do |day| %>
		<div class="col-xs-3">
			<p><strong><%= day.weekday %></strong></p>
			<p><%= "Open: #{day.opening.hour} : #{day.opening.min}" %></p>
			<p><%= "Close: #{day.closing.hour} : #{day.closing.min}" %></p>
		</div>
	<% end %>
</div>

<div class="col-md-10">
	<%= link_to 'Edit', edit_business_path(@business) %> |
	<%= link_to 'Back', businesses_path %>
</div>