config/routes.rb
Rails.application.routes.draw do
  resources :djs
  resources :business_hours, except: [:show, :edit, :update]
  resources :businesses
  resources :locations
  root 'welcome#index'
  get 'search_locations', to: 'locations#search'
  get 'find_locations', to: 'locations#find'
  get 'my_portfolio', to: 'locations#my_portfolio'
  get 'results', to: 'locations#result'
  get 'businesses/:id/edit_operations', to: 'businesses#edit_operations', as: "edit_operations"
  post 'businesses/:id/update_operations', to: 'businesses#update_operations', as: "update_operations" 

end

app/models/dj.rb
class Dj < ActiveRecord::Base
end

app/controllers/djs_controller.rb
class DjsController < ApplicationController
  before_action :set_dj, only: [:show, :edit, :update, :destroy]

  # GET /djs
  # GET /djs.json
  def index
    @djs = Dj.all
  end

  # GET /djs/1
  # GET /djs/1.json
  def show
  end

  # GET /djs/new
  def new
    @dj = Dj.new
  end

  # GET /djs/1/edit
  def edit
  end

  # POST /djs
  # POST /djs.json
  def create
    @dj = Dj.new(dj_params)

    respond_to do |format|
      if @dj.save
        format.html { redirect_to @dj, notice: 'Dj was successfully created.' }
        format.json { render :show, status: :created, location: @dj }
      else
        format.html { render :new }
        format.json { render json: @dj.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /djs/1
  # PATCH/PUT /djs/1.json
  def update
    respond_to do |format|
      if @dj.update(dj_params)
        format.html { redirect_to @dj, notice: 'Dj was successfully updated.' }
        format.json { render :show, status: :ok, location: @dj }
      else
        format.html { render :edit }
        format.json { render json: @dj.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /djs/1
  # DELETE /djs/1.json
  def destroy
    @dj.destroy
    respond_to do |format|
      format.html { redirect_to djs_url, notice: 'Dj was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dj
      @dj = Dj.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dj_params
      params.require(:dj).permit(:name, :genre)
    end
end

app/helpers/djs_helper.rb
module DjsHelper
end

app/views/djs/_form.html.slim
= form_for @dj do |f|
  - if @dj.errors.any?
    #error_explanation
      h2 = "#{pluralize(@dj.errors.count, "error")} prohibited this dj from being saved:"
      ul
        - @dj.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :genre
    = f.text_field :genre
  .actions = f.submit

app/views/djs/edit.html.slim
h1 Editing dj

== render 'form'

= link_to 'Show', @dj
'|
= link_to 'Back', djs_path

app/views/djs/index.html.slim
h1 Listing djs

table.table.table-striped
  thead
    tr
      th Name
      th Genre
      th
      th
      th

  tbody
    - @djs.each do |dj|
      tr
        td = dj.name
        td = dj.genre
        td = link_to 'Show', dj
        td = link_to 'Edit', edit_dj_path(dj)
        td = link_to 'Destroy', dj, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Dj', new_dj_path

app/views/djs/new.html.slim
h1 New dj

== render 'form'

= link_to 'Back', djs_path

app/views/djs/show.html.slim
p#notice = notice

p
  strong Name:
  = @dj.name
p
  strong Genre:
  = @dj.genre

= link_to 'Edit', edit_dj_path(@dj)
'|
= link_to 'Back', djs_path