config/routes.rb
Rails.application.routes.draw do
  resources :djs
  resources :business_hours, except: [:show, :edit, :update]
  resources :businesses
  resources :locations
  root 'welcome#index'
  get 'search_locations', to: 'locations#search'
  get 'find_locations', to: 'locations#find'
  get 'my_portfolio', to: 'locations#my_portfolio'
  get 'results', to: 'locations#result'
  get 'businesses/:id/edit_operations', to: 'businesses#edit_operations', as: "edit_operations"
  post 'businesses/:id/update_operations', to: 'businesses#update_operations', as: "update_operations" 

end

app/models/business_hour.rb
class BusinessHour < ActiveRecord::Base
	belongs_to :business
	belongs_to :hour
end

app/controllers/business_hours_controller.rb
class BusinessHoursController < ApplicationController
  before_action :set_business_hour, only: [:show, :edit, :update, :destroy]

  # GET /business_hours
  # GET /business_hours.json
  def index
    @business_hours = BusinessHour.all
  end

  # GET /business_hours/1
  # GET /business_hours/1.json
  def show
  end

  # GET /business_hours/new
  def new
    @business_hour = BusinessHour.new
  end

  # GET /business_hours/1/edit
  def edit
  end

  # POST /business_hours
  # POST /business_hours.json
  def create
    @business_hour = BusinessHour.new(business_hour_params)

    respond_to do |format|
      if @business_hour.save
        format.html { redirect_to @business_hour, notice: 'Business hour was successfully created.' }
        format.json { render :show, status: :created, location: @business_hour }
      else
        format.html { render :new }
        format.json { render json: @business_hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /business_hours/1
  # PATCH/PUT /business_hours/1.json
  def update
    respond_to do |format|
      if @business_hour.update(business_hour_params)
        format.html { redirect_to @business_hour, notice: 'Business hour was successfully updated.' }
        format.json { render :show, status: :ok, location: @business_hour }
      else
        format.html { render :edit }
        format.json { render json: @business_hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /business_hours/1
  # DELETE /business_hours/1.json
  def destroy
    @business_hour.destroy
    respond_to do |format|
      format.html { redirect_to business_hours_url, notice: 'Business hour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business_hour
      @business_hour = BusinessHour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_hour_params
      params.require(:business_hour).permit(:business_id, :hour_id)
    end
end

app/helpers/business_hours_helper.rb
module BusinessHoursHelper
end

app/views/business_hours/_form.html.erb
<%= form_for(@business_hour) do |f| %>
  <% if @business_hour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business_hour.errors.count, "error") %> prohibited this business_hour from being saved:</h2>

      <ul>
      <% @business_hour.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :business_id %><br>
    <%= f.number_field :business_id %>
  </div>
  <div class="field">
    <%= f.label :hour_id %><br>
    <%= f.number_field :hour_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/business_hours/edit.html.erb
<h1>Editing Business Hour</h1>

<%= render 'form' %>

<%= link_to 'Show', @business_hour %> |
<%= link_to 'Back', business_hours_path %>

app/views/business_hours/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Business Hours</h1>

<table>
  <thead>
    <tr>
      <th>Business</th>
      <th>Hour</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @business_hours.each do |business_hour| %>
      <tr>
        <td><%= business_hour.business_id %></td>
        <td><%= business_hour.hour_id %></td>
        <td><%= link_to 'Show', business_hour %></td>
        <td><%= link_to 'Edit', edit_business_hour_path(business_hour) %></td>
        <td><%= link_to 'Destroy', business_hour, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Business hour', new_business_hour_path %>

app/views/business_hours/new.html.erb
<h1>New Business Hour</h1>

<%= render 'form' %>

<%= link_to 'Back', business_hours_path %>

app/views/business_hours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Business:</strong>
  <%= @business_hour.business_id %>
</p>

<p>
  <strong>Hour:</strong>
  <%= @business_hour.hour_id %>
</p>

<%= link_to 'Edit', edit_business_hour_path(@business_hour) %> |
<%= link_to 'Back', business_hours_path %>