config/routes.rb
Rails.application.routes.draw do
  resources :djs
  resources :business_hours, except: [:show, :edit, :update]
  resources :businesses
  resources :locations
  root 'welcome#index'
  get 'search_locations', to: 'locations#search'
  get 'find_locations', to: 'locations#find'
  get 'my_portfolio', to: 'locations#my_portfolio'
  get 'results', to: 'locations#result'
  get 'businesses/:id/edit_operations', to: 'businesses#edit_operations', as: "edit_operations"
  post 'businesses/:id/update_operations', to: 'businesses#update_operations', as: "update_operations" 

end

app/models/location.rb
class Location < ActiveRecord::Base
	geocoded_by :address
	after_validation :geocode

	def address
		[street, city, state, country].compact.join(', ')
	end

	def self.search_by_address(address, miles)
		locations = Location.near(address, miles)
		return locations
	end


end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    distance = (params[:distance].present?) ? params[:distance] : 10
    if params[:address].present?
      @locations = Location.near(params[:address], distance)
      render partial: 'lookup'
    else
      @locations = Location.all
      #render status: :not_found
      render partial: 'lookup'
    end
  end

def result
  @locations = Location.near('140 commowealth avenue, boston, MA', 20)
 
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:street, :city, :state, :country, :latitude, :longitude)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/_lookup.html.erb
<div id="location-lookup">
	<h3>Search for locations</h3>
	<%= form_tag find_locations_path, remote: true, method: :get, id: 'location-lookup-form' do %>
		<div class= "form-group row no-padding text-center col-md-12">
			<div class = "col-md-10">
				<%= text_field_tag :currentLocation, params[:currentLocation], 
				placeholder: "please enter your current location", autofocus: true,
				class: "form-control search-box input-lg" %>
			</div>	
			<div class= "col-md-2">
				<%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
					<i class="fa fa-search"></i> Look up places
				<% end %>
			</div>
		</div>
	<% end %>
<% if @locations %>
	<% if @locations.size > 0 %> 
		<div id="location-lookup-results" class="well results-block col-md-10">
			<table class="search-results-table col-md-12" >
				<tbody>
					<% @locations.each do |location| %>
						<tr>
							<td><strong>Street:</strong> <%= location.street %></td>
							<td><strong>Logitude:</strong> <%= location.longitude %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	<% else %>
		<p class = "lead col-md-12">
			No match for this search criteria
		</p>
	<% end %>
<% end %>

<div id="location-lookup-errors"></div>

</div>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Locations</h1>

<table>
  <thead>
    <tr>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.street %></td>
        <td><%= location.city %></td>
        <td><%= location.state %></td>
        <td><%= location.country %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/my_portfolio.html.erb
<%= render 'lookup' %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/result.html.erb
<div id="location-lookup">
<h3>Search for locations</h3>
	<%= form_tag results_path, remote: true, method: :get, id: 'location-lookup-form' do %>
<% if @locations %>
	<% if @locations.size > 0 %> 
		<div id="results" class="well results-block col-md-10">
			<table class="search-results-table col-md-12" >
				<tbody>
					<% @locations.each do |location| %>
						<tr>
							<td><strong>Street:</strong> <%= location.street %></td>
							<td><strong>Logitude:</strong> <%= location.longitude %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	<% else %>
		<p class = "lead col-md-12">
			No match for this search criteria
		</p>
	<% end %>
<% end %>

<div class= "col-md-2">
				<%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
					<i class="fa fa-search"></i> Look up places
				<% end %>
			</div>

			<% end %>
			</div>

<script>
	var init_location_lookup;

init_location_lookup = function(){
	$('#location-lookup-form').on('ajax:success', function(event, data, status){
		$(".well results-block col-md-10").replaceWith(data);
		init_location_lookup();
	});

	$('#location-lookup-form').on('ajax:error', function(event, xhr, status, error){
		$('#location-lookup-results').replaceWith('  ');
		$('#location-lookup-errors').replaceWith('Location was not found');
	});
}


$(document).ready(function(){
	init_location_lookup()
})
</script>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Street:</strong>
  <%= @location.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @location.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @location.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @location.country %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<% for local in @location.nearbys(10) %>
  <ul>
    <li> <%= local.street %> </li>
    <li> <%= local.city %> </li>
    <li> <%= local.distance.round(2) %> miles </li>
  </ul>
<% end %>
<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>